autorespondez/blueprints/page/views.py
from flask import Blueprint, render_template

page = Blueprint('page', __name__, template_folder='templates')


@page.route("/")
def home():
	return render_template('page/home.html')


@page.route("/terms")
def terms():
	return render_template('page/terms.html')


@page.route("/privacy")
def privacy():
	return render_template('page/privacy.html')   	

autorespondez/templates/layouts/base.html
<!doctype html>
<html class="no-js" lang="en">
    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        <!-- ========== VIEWPORT META ========== -->
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />

        <!-- ========== PAGE TITLE ========== -->
        <title>{% block title %}{% endblock %}</title>

        <!-- ========== META TAGS ========== -->
        <meta name="description" content="{% block meta_description %}{% endblock %}">
        <meta name="keywords" content="marketing automation, marketing, saas">
        <meta name="author" content="The Green Brain">

        <!-- ========== FAVICON & APPLE ICONS ========== -->
        <link rel="shortcut icon" href="images/favicon.png">
        <link rel="apple-touch-icon" href="images/apple-touch-icon.png">

        <!-- ========== MINIFIED VENDOR CSS ========== -->
        <link rel="stylesheet" href="{{ url_for('static', filename='styles/vendor.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='styles/main.css') }}">

        <!-- ========== MODERNIZR ========== -->
    	<script src="{{ url_for('static', filename='scripts/vendor/modernizr.js') }}"></script>
    </head>

    <body class="animsition">

        <!-- ========== NAVIGATION ========== -->
    	<nav class="navbar yamm navbar-fixed-top" role="navigation">
    		<div class="container-fluid">
    			<div class="navbar-header">
    				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
    					<span class="sr-only">Toggle navigation</span>
    					<span class="icon-bar"></span>
    					<span class="icon-bar"></span>
    					<span class="icon-bar"></span>
    				</button> <!-- end navbar-toggle -->
    				<a class="navbar-brand" href="index.html">
    					<img src="images/light-logo.svg" alt="SoftEase Logo" class="light-logo">
    					<img src="images/dark-logo.svg" alt="SoftEase Logo" class="dark-logo">
    				</a> <!-- end navbar-brand -->
    			</div> <!-- end navbar-header -->

    			<div id="navbar" class="navbar-collapse collapse">
    				<ul class="nav navbar-nav pull-right">
    					<li class="active dropdown">
    						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Home <span class="caret"></span></a>
                            <ul class="dropdown-menu animated fadeIn">
    							<li>
                                    <div class="yamm-content">
                                        <div class="nav-col">
                                            <ul>
                                                <li><a href="index.html">Default Home</a></li>
                                                <li><a href="index-animated-bg.html">Animated Background</a></li>
                                                <li><a href="index-animated-text.html">Animated Text</a></li>
                                                <li><a href="index-simple.html">Animated + Image</a></li>
                                                <li><a href="index-slider.html">Home With Slider</a></li>
                                                <li><a href="index-boxed.html">Boxed Home</a></li>
                                            </ul>
                                        </div> <!-- end nav-col -->
                                    </div> <!-- end yamm-content -->
    							</li>
    						</ul> <!-- end dropdown-menu -->
    					</li>
    					<li class="dropdown">
    						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Features <b class="caret"></b></a>
    						<ul class="dropdown-menu animated fadeIn">
    							<li>
    							    <div class="yamm-content">
                                        <div class="nav-col">
                                            <ul>
                                                <li><h5>FEATURES</h5></li>
                                                <li><a href="#">Demo Link</a></li>
                                                <li><a href="#">Demo Link</a></li>
                                                <li><a href="#">Demo Link</a></li>
                                                <li><a href="#">Demo Link</a></li>
                                            </ul>
                                        </div> <!-- end nav-col -->
                                        <div class="nav-col">
                                            <ul>
                                                <li><h5>FEATURES</h5></li>
                                                <li><a href="#">Demo Link</a></li>
                                                <li><a href="#">Demo Link</a></li>
                                                <li><a href="#">Demo Link</a></li>
                                                <li><a href="#">Demo Link</a></li>
                                            </ul>
                                        </div> <!-- end nav-col -->
                                        <div class="nav-col dark-bg text-center">
                                            <h4>Take a demo for FREE!</h4>
                                            <p class="light-text">This is for demo purpose only. </p>
                                            <a href="sign-up.html" class="btn se-btn btn-rounded">SIGN UP</a>
                                        </div> <!-- end nav-col -->
                                    </div> <!-- end yamm-content -->
    							</li>
    						</ul> <!-- end dropdown-menu -->
    					</li> <!-- end dropdown (features) -->
    					<li class="">
    						<a href="feature-details.html" class="" >Feature Details </a>
    					</li>
                        <li><a href="pricing.html">Pricing</a></li>
                        <li><a href="about-us.html">About Us</a></li>
    					<li class="dropdown dd-left">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Pages <span class="caret"></span></a>
                            <ul class="dropdown-menu animated fadeIn">
    							<li>
                                    <div class="yamm-content">
                                        <div class="nav-col">
                                            <ul>
                                                <li><a href="features.html">Features</a></li>
                                                <li><a href="feature-details.html">Feature Details</a></li>
                                                <li><a href="login.html">Login</a></li>
                                                <li><a href="sign-up.html">Sign Up</a></li>
                                                <li><a href="faqs.html">FAQs</a></li>
                                                <li><a href="contact-us.html">Contact Us</a></li>
                                                <li><a href="privacy-policy.html">Privacy Policy</a></li>
                                            </ul>
                                        </div> <!-- end nav-col -->
                                    </div> <!-- end yamm-content -->
    							</li>
    						</ul>
                        </li> <!-- end dropdown.dd-left (pages) -->

                        <li class="dropdown dd-left">
    						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Blog <b class="caret"></b></a>
    						<ul class="dropdown-menu animated fadeIn">
    							<li>
    							    <div class="yamm-content">
                                        <div class="nav-col">
                                            <ul>
                                                <li><h5>Default</h5></li>
                                                <li><a href="blog.html">Default Layout</a></li>
                                                <li><a href="blog-2.html">Layout 2</a></li>
                                                <li><a href="blog-left-sidebar.html">Left Sidebar</a></li>
                                                <li><a href="blog-2-left-sidebar.html">Left Sidebar 2</a></li>
                                            </ul>
                                        </div> <!-- end nav-col -->
                                        <div class="nav-col">
                                            <ul>
                                                <li><h5>Single Post</h5></li>
                                                <li><a href="blog-single-post.html">Default</a></li>
                                                <li><a href="blog-single-left-sidebar.html">Left Sidebar</a></li>
                                                <li><a href="blog-single-post-full.html">Full Width</a></li>
                                            </ul>
                                        </div> <!-- end nav-col -->
                                        <div class="nav-col dark-bg text-center">
                                            <h4>Stay Updated!</h4>
                                            <p class="light-text">Subscribe to our newsletter. </p>
                                            <a href="sign-up.html" class="btn se-btn btn-rounded">SUBSCRIBE</a>
                                        </div> <!-- end nav-col -->
                                    </div> <!-- end yamm-content -->
    							</li>
    						</ul> <!-- end dropdown-menu -->
    					</li> <!-- end dropdown (blog) -->
    					<li class="nav-btn-wrap">
                            <span class="nav-btn"><a href="sign-up.html" class="btn se-btn-black btn-rounded">Sign Up</a></span>
                        </li>
    				</ul> <!-- end navbar-nav -->

    			</div> <!--end nav-collapse -->
    		</div> <!-- end container -->
    	</nav>



        <!-- ========== HEADER ========== -->
        <header class="header main-header header-style-3" id="circular-particles">
            {% block header %}{% endblock %}
        </header>

         {% block body %}{% endblock %}

        <!-- ========== FOOTER ========== -->
        <footer class="light-footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-2 col-sm-3 col-xs-6">
                        <img src="images/dark-logo.svg" alt="" class="footer-logo">
                    </div>

                    <div class="col-md-2 col-sm-3 col-xs-6">
                        <h6 class="mtn">HOME</h6>
                        <ul>
                            <li><a href="#">Parallax Background</a></li>
                            <li><a href="#">Animated Background</a></li>
                            <li><a href="#">Solid Color</a></li>
                            <li><a href="#">Gradient Background</a></li>
                        </ul>
                    </div>

                    <div class="col-md-2 col-sm-3 col-xs-6">
                        <h6 class="mtn">PAGES</h6>
                        <ul>
                            <li><a href="#">About Us</a></li>
                            <li><a href="#">Our Team</a></li>
                            <li><a href="#">Pricing</a></li>
                            <li><a href="#">Features</a></li>
                        </ul>
                    </div>

                    <div class="col-md-2 col-sm-3 col-xs-6">
                        <h6 class="mtn">OTHER</h6>
                        <ul>
                            <li><a href="#">Sign Up</a></li>
                            <li><a href="#">Login</a></li>
                            <li><a href="{{ url_for('page.privacy') }}">Privacy Policy</a></li>
                            <li><a href="{{ url_for('page.terms') }}">Terms of Service</a></li>
                        </ul>
                    </div>

                    <div class="col-md-4 col-sm-8 col-sm-offset-2 col-md-offset-0">
                        <h6 class="mtn">SUBSCRIBE</h6>
                        <div class="input-group">
                            <input type="email" class="form-control inp-rounded" placeholder="Enter your email id">
                            <span class="input-group-btn">
                                <button class="btn se-btn btn-rounded" type="button">Subscribe!</button>
                            </span> <!-- end input-group-btn -->
                        </div><!-- end input-group -->
                        <p class="text-center text-muted">We don't spam!</p>
                    </div>
                </div> <!-- end row -->

                <div class="row footer-bottom">
                    <div class="col-md-6">
                        <p>Copyright &copy; SoftEase Technologies. 2016. All Rights Reserved.</p>
                    </div>

                    <div class="col-md-6 text-right">
                        <h6><a href="#">FACEBOOK</a></h6>
                        <h6><a href="#">TWITTER</a></h6>
                        <h6><a href="#">LINKEDIN</a></h6>
                        <h6><a href="#">GOOGLE PLUS</a></h6>
                    </div>
                </div> <!-- end footer-bottom -->
            </div> <!-- end container -->
        </footer>


    	<script src="{{ url_for('static', filename='scripts/vendor.js') }}"></script>

        <!-- ========== MINIFIED PLUGINS JS ========== -->
    	<script src="{{ url_for('static', filename='scripts/plugins.js') }}"></script>

    	<script src="{{ url_for('static', filename='scripts/main.js') }}"></script>

        <script src="{{ url_for('static', filename='scripts/init-animation-circle.js') }}"></script>
    </body>

</html>